title: Jason Ranoa
description: Jason Ranoa's personal website and sandbox.
theme: just-the-docs
url: "https://jasonranoa.github.io"

permalink: pretty
favicon_ico: "/assets/images/favicon.ico"

search_enabled: false
heading_anchors: false
back_to_top: false
gh_edit_link: false


# COLORS
color_scheme: dark

# AUXILIARY LINKS
aux_links:
  "Visit me at GitHub":
    - "//github.com/jasonranoa"
  "Email me @ jasonranoa.math@gmail.com":
    - "mailto: jasonranoa.math@gmail.com"
aux_links_new_tab: true


# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all