title: Jason's Sandbox
# logo: /assets/img/logo.png
description:
    Hi, there! I'm a graduate student at Oregon State University (OSU). Included in the website is my CV and some personal projects.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
navigation:
  - pagename: 'Resume/CV'
    folder: '/resume'
  - pagename: 'MTH 53X Topology Solutions'
    folder: '/mth53x'
